### ISSUE TITLE
Request help on your code

### ISSUE THREAD

**Issue by glhfgg1024** [dineshreddy91/Semantic_Motion_Segmentation#1]
Hi, firstly thanks a lot for sharing your code!

I've read your paper on this repository and read your code, it seems the code didn't contain the implementation on joint CRF learning. It seems there is no difference between your denseCRF with the official denseCRF. But in your paper, the joint denseCRF has a different mean-field inference procedure. Did I miss something? I'm appreciated if your could give some suggestions. Thanks!

**Comment by dineshreddy91** [comment]
Hi thanks for the interest in the project. I am not allowed to upload the exact contributions of the paper as they are being patented by our funding agency. i have released all the opensource libraries i have used to implement the paper for reference.

**Comment by glhfgg1024** [comment]
Sadly but understood. Still grateful for your kind reply! I'd greatly appreciated that if you could describe this in the README of your repository. I really couldn't find the core implementation related to your paper.
